### ISSUE TITLE
Submit individual cleaner scripts

### ISSUE THREAD

**Issue by thelamehacker** [thelamehacker/system-monitor#11]
Post an update here when the individual cleaning scripts are finished. Currently they are functional but do not tag the machine uniquely by generating LogID from machineID.

LogID = { machineID + data + log number}

Currently the concurrent work on cleaners is being done in a fork here - https://github.com/itsalways5am/system-monitor-1/tree/master/log_cleaners

**Comment by itsalways5am** [comment]
In progress! I need your advice on the timing issue.

**Comment by itsalways5am** [comment]
Complete! Ready for testing. Note - you will need to manually add test machineID as I deleted the info from the scripts here in Git!

https://github.com/itsalways5am/system-monitor-1/tree/master/log_cleaners

**Comment by itsalways5am** [comment]
Working on extracting day of the week.

**Comment by thelamehacker** [comment]
Closing this as mark2 prototype testing has been completed.
