### ISSUE TITLE
Report consistency challenges when done with each .log script

### ISSUE THREAD

**Issue by itsalways5am** [thelamehacker/system-monitor#4]
I will report to you some consistency issues with cleaning log files. It's a system that we can use in the future. But I wouldn't worry now about the time and date because it's something I can work on and if I submit to you every consistency issue, then my scripts would need to be changed (which is fine) - will be shorter :) and more efficient I think.

What do you think?

**Comment by thelamehacker** [comment]
Redid the logger component for consistency. Closing the issue.
